# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bartosz Jabłonka
title: Automation Engineer
email: bjablonka@wp.pl
website: bjablonka.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bartosz Jabłonka and I'm an automation engineer. I'm currently employed at <mark>ZETA</mark> Poland in Gdańsk. I'm interested and would like to develop in the fields of new technologies, IoT, PLC programming.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cable selector tool
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Looking for tool for voltage drop and cable selector? Please try my app. You can download it [here](KabelSelektor.zip)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZETA PL Sp. z o.o.
        link: zeta.com
        # link_text: boringcompany.com
        sub_title: Automation/BMS/EMS Engineer
        caption: Present
        quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           At ZETA PL I'm responsible for development of concept, basic, detail and as-built designs for facility and process automation systems
                    
      - layout: left
        title: Exyte Poland
        link: exyte.net
        # link_text: boringcompany.com
        sub_title: Automation/I&C Engineer
        # caption: May 2022 - Present
        quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           At Exyte, I work as an automation engineer. During these two I worked on:
           * <mark>Ohly GmbH</mark> Hamburg – basic, detail design and as-built documentation engineer for BMS, IT/OT network, security systems for the newly constructed spray dryer building
           * Center for Development and Production of Oncological Drugs <mark>Polfa SA</mark> in Tarchomin – as-built documentation engineer for BMS/EMS, IT, security and safety systems
      
      - layout: left
        title: B&W Usługi Ogólnobudowlane
        link: biw.gda.pl
        # link_text: boringcompany.com
        sub_title: Electrical Engineer
        # caption: May 2022 - Present
        quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           My tasks were a.o.
           * PLC programming (Siemens S7-1200, Horner, Logo, HMI Astraada)
           * configuration and start-up of network devices, surveillance and security systems, CCTV, FAS
           * cost estimation of teletechnical, low-voltage installations
           * servicing and maintenance of control switchboards of pump stations
      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gdańsk University of Technology
        # caption: ... - ...
        sub_title: Faculty of Electrical and Control Engineering
        quote: >
          Gdańsk University of Technology was founded in 1904, so last year it celebrated its 120th birthday.
        description: | # this will include new lines to allow paragraphs
          Studying at Gdansk Tech was an excellent experience. I graduated as Bachelor of Science in Electrical Engineering.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in automation engineering, I also like to take a camera and explore unfamiliar places. Some of my other interests and hobbies are:
      - IoT
      - retrocomputing - especially Commodore C64 and Amiga computers
      - ancient programming languages, like: assembler, AMOS and others
      - Rapsberry Pi, ESP and other microcontrollers
     # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
